---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - monitoring.example.com
  resources:
  - etcdmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.example.com
  resources:
  - etcdmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.example.com
  resources:
  - etcdmonitors/status
  verbs:
  - get
  - patch
  - update
